version: '3'
services:
  frp_server:
    image: geektr/frp
    restart: always
    env_file:
      - "$secrets_dir/frp/frp.env"
    volumes:
      - "$service_dir/conf/frp/frps.ini:/etc/frp/frps.ini:ro"
    network_mode: "host"
